from myapp.views.admin.thing import *
from myapp.views.admin.category import *
from myapp.views.admin.user import *
from myapp.views.admin.news import *
from myapp.views.admin.case import *
from myapp.views.admin.faq import *
from myapp.views.admin.overview import *
from myapp.views.admin.opLog import *
from myapp.views.admin.errorLog import *
from myapp.views.admin.cdn import *
